# configmap.yaml
# TODO: Create a ConfigMap named "app-config"
#   with keys APP_GREETING=Welcome and APP_VERSION=1.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # TODO: Add key-value pairs
